import fs from 'fs';
import path from 'path';

/**
 * TravelSplit Documentation Agent
 * Automatically scans the codebase, inspects models, endpoints, components,
 * and regenerates/updates project documentation files in docs/
 */

const ROOT_DIR = process.cwd();
const DOCS_DIR = path.join(ROOT_DIR, 'docs');

if (!fs.existsSync(DOCS_DIR)) {
  fs.mkdirSync(DOCS_DIR, { recursive: true });
}

function countLines(filePath: string): number {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    return content.split('\n').length;
  } catch {
    return 0;
  }
}

function scanFiles(dir: string, extensions: string[] = ['.ts', '.tsx', '.js', '.jsx']): string[] {
  let results: string[] = [];
  if (!fs.existsSync(dir)) return results;

  const list = fs.readdirSync(dir);
  list.forEach((file) => {
    const fullPath = path.join(dir, file);
    const stat = fs.statSync(fullPath);
    if (stat && stat.isDirectory()) {
      if (file !== 'node_modules' && file !== 'dist' && file !== '.git') {
        results = results.concat(scanFiles(fullPath, extensions));
      }
    } else {
      if (extensions.some((ext) => file.endsWith(ext))) {
        results.push(fullPath);
      }
    }
  });
  return results;
}

export function runDocAgent() {
  console.log('🤖 TravelSplit Documentation Agent starting codebase scan...');

  const srcFiles = scanFiles(path.join(ROOT_DIR, 'src'));
  const serverFiles = scanFiles(path.join(ROOT_DIR, 'server'));
  const convexFiles = scanFiles(path.join(ROOT_DIR, 'convex'));
  const testFiles = scanFiles(path.join(ROOT_DIR, 'src', 'core', '__tests__'));

  const totalTsFiles = srcFiles.length + serverFiles.length + convexFiles.length;
  let totalLines = 0;
  [...srcFiles, ...serverFiles, ...convexFiles].forEach((f) => {
    totalLines += countLines(f);
  });

  const timestamp = new Date().toISOString();

  // Generate CODEBASE_INDEX.md
  const codebaseIndexContent = `# Codebase Inventory & Symbol Index

> Auto-generated by **TravelSplit Documentation Agent** on \`${timestamp}\`.

---

## 📊 Summary Statistics
- **Total Source Files**: ${totalTsFiles} TypeScript / TSX files
- **Total Lines of Code**: ${totalLines.toLocaleString()} lines
- **Test Suites**: ${testFiles.length} test files

---

## 📂 Source Code Structure

### 1. Presentation & iOS UI Components (\`src/components/\`)
${srcFiles
  .filter((f) => f.includes('components'))
  .map((f) => `- [\`${path.relative(ROOT_DIR, f).replace(/\\/g, '/')}\`](../${path.relative(ROOT_DIR, f).replace(/\\/g, '/')}) (${countLines(f)} lines)`)
  .join('\n')}

### 2. Core Domain & Mathematical Engines (\`src/core/\`)
${srcFiles
  .filter((f) => f.includes('core') && !f.includes('__tests__'))
  .map((f) => `- [\`${path.relative(ROOT_DIR, f).replace(/\\/g, '/')}\`](../${path.relative(ROOT_DIR, f).replace(/\\/g, '/')}) (${countLines(f)} lines)`)
  .join('\n')}

### 3. State Management (\`src/store/\`)
${srcFiles
  .filter((f) => f.includes('store'))
  .map((f) => `- [\`${path.relative(ROOT_DIR, f).replace(/\\/g, '/')}\`](../${path.relative(ROOT_DIR, f).replace(/\\/g, '/')}) (${countLines(f)} lines)`)
  .join('\n')}

### 4. Database & Repositories (\`src/db/\`)
${srcFiles
  .filter((f) => f.includes('db'))
  .map((f) => `- [\`${path.relative(ROOT_DIR, f).replace(/\\/g, '/')}\`](../${path.relative(ROOT_DIR, f).replace(/\\/g, '/')}) (${countLines(f)} lines)`)
  .join('\n')}

### 5. Backend Server (\`server/\`)
${serverFiles
  .map((f) => `- [\`${path.relative(ROOT_DIR, f).replace(/\\/g, '/')}\`](../${path.relative(ROOT_DIR, f).replace(/\\/g, '/')}) (${countLines(f)} lines)`)
  .join('\n')}

### 6. Convex Serverless Database (\`convex/\`)
${convexFiles
  .map((f) => `- [\`${path.relative(ROOT_DIR, f).replace(/\\/g, '/')}\`](../${path.relative(ROOT_DIR, f).replace(/\\/g, '/')}) (${countLines(f)} lines)`)
  .join('\n')}
`;

  fs.writeFileSync(path.join(DOCS_DIR, 'CODEBASE_INDEX.md'), codebaseIndexContent, 'utf-8');

  // Generate PROJECT_OVERVIEW.md
  const projectOverviewContent = `# TravelSplit iOS — Project Overview & Documentation Map

> Auto-generated and maintained by **Documentation Agent**. Last refreshed: \`${timestamp}\`.

---

## 📚 Complete Documentation Index

| Document | Purpose & Contents |
| :--- | :--- |
| **[Architecture Documentation](./ARCHITECTURE.md)** | System layers, presentation HIG structure, data flow, and synchronization. |
| **[Core Mathematical Engines](./CORE_ENGINES.md)** | Exact formulas for Equal, Exact, %, Shares, Itemized Bill with tax/tip, and Greedy Bipartite Debt Minimization. |
| **[API & Convex Reference](./API_AND_CONVEX_REFERENCE.md)** | Express REST API endpoints, parameters, responses, and Convex serverless schema/functions. |
| **[RBAC & Security Guide](./RBAC_SECURITY.md)** | Role permissions matrix (Owner, Editor, Viewer) and access control enforcement. |
| **[Codebase Inventory & Index](./CODEBASE_INDEX.md)** | Automated file index with lines of code and symbol mappings. |

---

## 🛠️ Automated Documentation Agent
This codebase includes an automated documentation scanner in \`scripts/doc-agent.ts\`.
Whenever you commit changes or trigger CI/CD, the agent scans the codebase, re-computes code metrics, updates file mappings, and refreshes the documentation suite automatically!

To run manually:
\`\`\`bash
npm run doc-agent
\`\`\`
`;

  fs.writeFileSync(path.join(DOCS_DIR, 'PROJECT_OVERVIEW.md'), projectOverviewContent, 'utf-8');

  console.log('✅ Documentation Agent successfully generated and refreshed docs!');
}

runDocAgent();
